# Generated by Django 4.1 on 2023-04-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0005_alter_fotografia_data_fotografia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotografia",
            name="foto",
            field=models.ImageField(blank=True, upload_to="fotos/%Y/%m/%d/"),
        ),
    ]
